### ISSUE TITLE
Memory issues

### ISSUE THREAD

**Issue by fennecdjay** [jwerle/url.h#4]
As you can see [here](https://travis-ci.org/fennecdjay/zpm-zsh/jobs/201778098#L253), it looks like url.h is leaking memory. I'd like to volonteer for a Pull Request fixing those issues.
@jwerle What do you think?

**Comment by jwerle** [comment]
I'd happily accept a PR. Nice catch

**Comment by fennecdjay** [comment]
Great.
Thanks for the fast answer.

**Comment by fennecdjay** [comment]
On my way to the PR, I've noticed that `protocol` variable in  `url_get_protocol` needs to be null terminated.
I know two ways to fix this, but I'd like to know which you prefer, or if you know another, as none is present yet in the code.
they are:

  * use of memset.
  * use of calloc.

using strlen fails because its input is not null terminated.

----------

gcc also complains about two `set but not used variables`, is it ok to remove them?

**Comment by jwerle** [comment]
@fennecdjay `memset` is preferred :]

**Comment by fennecdjay** [comment]
looking at [this](https://gist.github.com/fennecdjay/c1b9299061abe28986810cf6c061d3af), there's quite a lot to do.

Is it ok to add

```c
void url_test(char* str, char* (func)(char*), char* url) {
    char* tmp_url = malloc(strlen(url) * sizeof(char) + 1);
    strcpy(tmp_url, tmp_url);
    char* value = func(url);
    assert(0 == strcmp(str, value));
    free(value);
    free(tmp_url);
}
```

to test.c, to ensure freeing?

also, almost all calls to 
```c
myvar = malloc(sizeof(char));
```

lead to `read/write/uninitialized` errors.

data->port and data need to be freed in `url_free()`.

---------

I'll ensure:
  * check every call to malloc.
  * malloc every pointer with good size.
  * no Read/write/uninitialzed errors.
  * every memory is freed.
  * free unused variables.
----------

eveything is ready yet on my platform, I'm now going to figure how to organize commits so that it leads to clean history.

**Comment by jwerle** [comment]
Awesome that sounds great to me !

**Comment by fennecdjay** [comment]
A last question to make it clear:
to ensure proper memory freeing, I need more variables, as you sometimes use, for instance

```c
fmt_url = strdup(url);
fmt_url = strff(fmt_url, l);
```
It would better be something like:
```c
char* fmt_url;
char* xxx = strdup(url)
fmt_url = strff(xxx, l);
xxx = xxx -l;
free(xxx);
```

Any hint to a naming convention?
I've just been prefixing those with`_` for now (e.g. : `_fmt_url`).

**Comment by jwerle** [comment]
I have no preference

**Comment by takakawa** [comment]
I have mem leak problems too!Hope you fix it soon!
